---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}-svc
spec:
  type: ClusterIP
  selector:
    app: {{.Values.appName}}
  ports:
    - name: https
      protocol: TCP
      port: 8080
      targetPort: 8080
